### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by Zemgad** [Selene-T/Tracker-of-Time#1]
I made sure I had the correct version for the updated version of bizhawk, and when I hit start with both the emulator (rom running as well) and the tracker running, the name of the app gains (emuhawk), freezes for a few seconds, then start becomes stop and nothing else changes. no matter what i do in game it doesn't update either. is there and FAQ or a readme i'm missing?

**Comment by Selene-T** [comment]
The x64 version should work with BizHawk 2.7 and 2.8 official releases.  If it is saying (emuhawk) then it is the x64 version and is finding the emulator. If it is not turning itself off, then it is finding the game (checks you are running Ocarina of Time) so it should be calibrated properly. Are you loaded into a saved game?

**Comment by Zemgad** [comment]
It is turning itself off after 30s or so, so i guess it's not finding the game then. I meant to mention that but slipped thru the cracks. What do you mean by loaded into a "saved" game?

**Comment by Zemgad** [comment]
Nevermind

**Comment by Zemgad** [comment]
Nevermind, your "saved game" comment pointed me i the right direction and i got it working. If i may make a suggestion: include a readme or a how to because as a first timer to an auto-tracker this was a nightmare.
