### ISSUE TITLE
Grotto Randomizer & Notes

### ISSUE THREAD

**Issue by Kankur0** [Selene-T/Tracker-of-Time#10]
Any chance of adding support for Grotto Randomizer logic?

If it has it and I'm just doing something wrong, please let me know, but it seems to not know that the grottos aren't randomized and keeps telling me to check the normal location for the grotto.

Also, the ability to add noted would be handy, but obviously not necessary since notepad is a thing.

**Comment by Selene-T** [comment]
I was unable to find a solid way to detect what grottos are which, without reading the actual ROM file (not in the scope available to me). As for notes, yea, the option would just be to add a new tab for just notepad, not really useful.

**Comment by Kankur0** [comment]
> I was unable to find a solid way to detect what grottos are which, without reading the actual ROM file (not in the scope available to me). As for notes, yea, the option would just be to add a new tab for just notepad, not really useful.

Ah, dang, The grottos are pretty confusing at times, but not that bad. Understandable though. 

As for the notes, I don't blame you for not wanting to spend time on that.
