### ISSUE TITLE
Force Check Bug

### ISSUE THREAD

**Issue by Kankur0** [Selene-T/Tracker-of-Time#12]
Forcing "Cow: Grotto Near Gerudo Valley" doesn't clear it, instead it either shows or hides "GS: Grotto Near Gerudo Valley (A)" and brings back "Cow: Grotto Near Gerudo Valley" regardless.

**Comment by Selene-T** [comment]
Problem is fixed! Added in an additional "Cow" check, as it used to just use the base name for the check (which they shared).
