### ISSUE TITLE
Heart and Rupee Shuffle doesn't do anything

### ISSUE THREAD

**Issue by UrzaMTG** [Selene-T/Tracker-of-Time#13]
Enabling the "Heart and Rupee Shuffle" option (keyed to setStanding in the settings) doesn't seem to do anything currently. None of the freestanding checks get added to any areas (e.g. the recovery hearts in Saria's House, the items on her roof, the freestanding rupees scattered around Kokiri Forest, the shop rupee; just to use one area as an example).

**Comment by Selene-T** [comment]
Those are just placeholders currently.
