### ISSUE TITLE
[Issue] Map tracker not updating dungeon levels

### ISSUE THREAD

**Issue by SimplPixl** [Selene-T/Tracker-of-Time#2]
As a user of the tracker I'm wanting the ability to see my location on the map tracker update in dungeons so that when I change between levels I can see the checks required on other levels.

Currently the level remains on the level that the player entered on and doesn't update when progressing. If the levels are manually clicked the map doesn't update either.

Looks like this is implemented? but looks like it isn't currently working when used with SoH 3.0.1

**Comment by Selene-T** [comment]
Found the issue, fixing it!

**Comment by SimplPixl** [comment]
Awesome stuff loving your work!!

**Comment by Selene-T** [comment]
Uploaded v4.1.6a, x64 only since the changes only effect SoH.

**Comment by SimplPixl** [comment]
Legend! Will check it out later and close this off once tested :)

**Comment by SimplPixl** [comment]
Works brilliantly now! Fantastic work
