### ISSUE TITLE
[Issue] Save scumming/resetting removes medallion and stone locations

### ISSUE THREAD

**Issue by SimplPixl** [Selene-T/Tracker-of-Time#4]
As a user when I save scum/reset the game the locations of the medallions and stones manually entered will get wiped.

Ideally as the game is usually reset multiple times during a playthrough these locations need to remain until a new playthrough occurs.

**Comment by Selene-T** [comment]
Removing the full clear settings when reloading the game with SoH.

**Comment by SimplPixl** [comment]
Works perfect now :) closing this ticket
