### ISSUE TITLE
Map tracker doesn't update dungeon levels

### ISSUE THREAD

**Issue by Train1992** [Selene-T/Tracker-of-Time#8]
When i use Ship of Harkinian 5.0.1 and enter a Dungeon the Map doesn't updating when i change between floors,

i don't know what i'm doing wrong and this Problem exists only in Dungeons, the map updates correctly at all other locations.

this problem already existed in this closed issue: https://github.com/Selene-T/Tracker-of-Time/issues/2

**Comment by Selene-T** [comment]
Thank you for bringing this to my attention. Fixed it in v4.2.2, and have added a note to remind me to re-align that variable when new SoH updates so this should hopefully not happen again.
